FROM quay.io/openshifttest/fcos-bm:base

COPY root/ /

RUN set -x; pip3 install --target=$(ls -1d /usr/lib/python* | head -n1)/site-packages/ redfish pandas netaddr wheel junos-eznc fastapi 'uvicorn[standard]' \
    google-auth google-api-python-client python-multipart \
    && systemctl preset-all
